### ISSUE TITLE
NOISSUE: one or more of the provided commands ended abnormally

### ISSUE THREAD

**Issue by hypergnash** [nicolas-van/multirun#1]
It would be nice to know which one of the commands failed / ended:

Affects: "multirun: one or more of the provided commands ended abnormally"

For example: 
 "multirun: command #1 ended abnormally"
 "multirun: command #1, #3 ended abnormally"

**Comment by nicolas-van** [comment]
You already have that information when running in verbose mode: multirun: command %s with pid %d exited abnormally
