### ISSUE TITLE
Prebuilt arm64 binaries

### ISSUE THREAD

**Issue by tpetry** [nicolas-van/multirun#12]
With more and more ARM computers now in use due to new Apple Silicon computers, it would be very nice to provide prebuilt amd64 and arm64 in github releases for easy docker container creation

**Comment by blackandred** [comment]
Exactly, also it would be nice to use this application in multiarch images.

**Comment by nicolas-van** [comment]
I completely agree.

Unfortunately it's easier said than done. I think the best solution nowadays would be to use cross-compilation with Clang, but my Makefile skills are quite insufficient to perform that task.

So if anyone could point a *good* tutorial on how to do it (or even better: a project already doing it in a Github Action) I would be grateful.

**Comment by blackandred** [comment]
As a DevOps I can help only with Github Actions at least. I don't have enough knowledge with C or Makefile unfortunately.

**Comment by nicolas-van** [comment]
I'm working on something in this branch: https://github.com/nicolas-van/multirun/tree/github-actions

Currently I was able to get something that works on an AWS t4g instance. It will still take some time to get it consolidated, notably because I still don't know how to handle Musl builds. But it's a start.

**Comment by nicolas-van** [comment]
OK, I got it mostly right.

Now comes the real fun part: testing the result ^^

**Comment by nicolas-van** [comment]
Ok, done. I even included Raspberry Pi and Mac OS X builds while I was at it.
