### ISSUE TITLE
Published to Habitat

### ISSUE THREAD

**Issue by themightychris** [nicolas-van/multirun#9]
Hey there, thanks for building this!

I [made a plan](https://github.com/JarvusInnovations/habitat-plans/tree/master/multirun) for building and [published it](https://bldr.habitat.sh/#/pkgs/jarvus/multirun/latest/linux) to my favorite package manager, [Chef Habitat](https://www.habitat.sh/)

Anyone with the `hab` client installed could use the package like this:

```console
$ hab pkg install --binlink jarvus/multirun
» Installing jarvus/multirun
☁ Determining latest version of jarvus/multirun in the 'stable' channel
↓ Downloading jarvus/multirun/0.3.2/20190925020410
☛ Verifying jarvus/multirun/0.3.2/20190925020410
→ Using core/glibc/2.27/20190115002733
→ Using core/linux-headers/4.17.12/20190115002705
✓ Installed jarvus/multirun/0.3.2/20190925020410
★ Install of jarvus/multirun/0.3.2/20190925020410 complete with 1 new packages installed.
» Binlinking multirun from jarvus/multirun/0.3.2/20190925020410 into /hab/bin
★ Binlinked multirun from jarvus/multirun/0.3.2/20190925020410 to /hab/bin/multirun

$ multirun -h
Usage: multirun <options> command...
```

or like this:

```console
$ hab pkg install jarvus/multirun
» Installing jarvus/multirun
☁ Determining latest version of jarvus/multirun in the 'stable' channel
↓ Downloading jarvus/multirun/0.3.2/20190925020410
☛ Verifying jarvus/multirun/0.3.2/20190925020410
→ Using core/glibc/2.27/20190115002733
→ Using core/linux-headers/4.17.12/20190115002705
✓ Installed jarvus/multirun/0.3.2/20190925020410
★ Install of jarvus/multirun/0.3.2/20190925020410 complete with 1 new packages installed.

$ hab pkg exec jarvus/multirun multirun -h
Usage: multirun <options> command...
```

or like this:

```Dockerfile
FROM habitat/default-studio-x86_64-linux:0.85.0

RUN hab pkg install --binlink \
        jarvus/multirun \
        core/nginx \
        core/php

ENTRYPOINT ["multirun"]
```

If you're interested in publishing to Habitat yourself under your own origin name, just [register your own origin](https://bldr.habitat.sh/#/origins/create) and post what it is, and I'll open a PR for you adding the `plan.sh` in your repo root or under `habitat/` and configure it for building right from your repo. Then after you linked the repo, the Habitat bldr would handle rebuilding the binary on any push to `master` or update to glibc getting marked stable

**Comment by nicolas-van** [comment]
Yeah... sorry but I'm not really interested into maintaining a complex publishing pipeline for a system I don't personally use.

If you want to maintain that separately from the main multirun repo it's a good thing for Chef users :)
